import React, {Component} from 'react';
import "./privacy-policy.css"

class PrivacyPolicy extends Component {

    render() {
        return (<div className = "container">
                <p className="c12 m-5"><span
                    className="c0 ">FIANCHETTO - CHESS TOURNAMENT MANAGER </span></p>
                <p className="c6"><span className="c3">Privacy Policy</span></p>
                <p className="c2"><span className="c3">Last updated: April 20, 2020</span></p>
                <p className="c2"><span className="c3">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</span>
                </p>
                <p className="c2"><span className="c3">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This </span>
                </p>
                <h2 className="c5" id="h.svlu32k207im"><span className="c0">Definitions</span></h2>
                <p className="c2"><span
                    className="c3">For the purposes of this Privacy Policy:</span></p>
                <p className="c2"><span className="c1">You</span><span className="c3">&nbsp;means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</span>
                </p>
                <p className="c2"><span className="c1">Company</span><span
                    className="c3">&nbsp;(referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Fianchetto Chess Tournament Manager.</span>
                </p>
                <p className="c2"><span className="c1">Affiliate</span><span
                    className="c3">&nbsp;means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</span>
                </p>
                <p className="c2"><span className="c1">Account</span><span
                    className="c3">&nbsp;means a unique account created for You to access our Service or parts of our Service.</span>
                </p>
                <p className="c2"><span className="c1">Website</span><span
                    className="c3">&nbsp;refers to Fianchetto Chess Tournament Manager, accessible from https://fianchetto-client.herokuapp.com/</span>
                </p>
                <p className="c2"><span className="c1">Service</span><span
                    className="c3">&nbsp;refers to the Website.</span>
                </p>
                <p className="c2"><span className="c1">Country</span><span
                    className="c3">&nbsp;refers to: Massachusetts, United States</span>
                </p>
                <p className="c2"><span className="c1">Service Provider</span><span
                    className="c3">&nbsp;means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</span>
                </p>
                <p className="c2"><span className="c1">Third-party Social Media Service</span><span
                    className="c3">&nbsp;refers to any website or any social network website through which a User can log in or create an account to use the Service.</span>
                </p>
                <p className="c2"><span className="c1">Personal Data</span><span
                    className="c3">&nbsp;is any information that relates to an identified or identifiable individual.</span>
                </p>
                <p className="c2"><span className="c1">Cookies</span><span className="c3">&nbsp;are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</span>
                </p>
                <p className="c2"><span className="c1">Usage Data</span><span
                    className="c3">&nbsp;refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</span>
                </p>
                <p className="c2"><span
                    className="c3">Collecting and Using Your Personal Data</span></p>
                <h2 className="c5" id="h.uzbti0it6y9l"><span
                    className="c0">Types of Data Collected</span></h2>
                <h3 className="c7" id="h.jsmuiyrqzh2d"><span className="c1 c4">Personal Data</span>
                </h3>
                <p className="c2"><span className="c3">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</span>
                </p>
                <p className="c2"><span className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;Email address</span>
                </p>
                <p className="c2"><span className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;First name and last name</span>
                </p>
                <p className="c2"><span className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;Usage Data</span>
                </p>
                <h3 className="c7" id="h.klho4se1sowm"><span className="c4 c1">Usage Data</span>
                </h3>
                <p className="c2"><span className="c3">Usage Data is collected automatically when using the Service.</span>
                </p>
                <p className="c2"><span className="c3">Usage Data may include information such as Your Device&#39;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</span>
                </p>
                <p className="c2"><span className="c3">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</span>
                </p>
                <p className="c2"><span className="c3">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</span>
                </p>
                <h3 className="c7" id="h.ke681qntsah5"><span className="c4 c1">Tracking Technologies and Cookies</span>
                </h3>
                <p className="c2"><span className="c3">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</span>
                </p>
                <p className="c2"><span className="c3">You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</span>
                </p>
                <p className="c2">
                    <span>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser. Learn more about cookies:</span><span><a
                    className="c9"
                    href="https://www.google.com/url?q=https://www.termsfeed.com/blog/cookies/&amp;sa=D&amp;ust=1587454237410000">&nbsp;</a></span><span
                    className="c8"><a className="c9"
                                      href="https://www.google.com/url?q=https://www.termsfeed.com/blog/cookies/&amp;sa=D&amp;ust=1587454237410000">All About Cookies</a></span><span
                    className="c3">.</span></p>
                <h2 className="c5" id="h.4yggd1j3h45o"><span className="c0">Use of Your Personal Data</span>
                </h2>
                <p className="c2"><span className="c3">The Company may use Personal Data for the following purposes:</span>
                </p>
                <p className="c2"><span
                    className="c1">To provide and maintain our Service</span><span className="c3">, including to monitor the usage of our Service.</span>
                </p>
                <p className="c2"><span className="c1">To manage Your Account:</span><span
                    className="c3">&nbsp;to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</span>
                </p>
                <p className="c2"><span className="c1">To contact You:</span><span
                    className="c3">&nbsp;To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&#39;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</span>
                </p>
                <p className="c2"><span className="c1">To provide You</span><span
                    className="c3">&nbsp;with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</span>
                </p>
                <p className="c2"><span className="c1">To manage Your requests:</span><span
                    className="c3">&nbsp;To attend and manage Your requests to Us.</span>
                </p>
                <p className="c2"><span
                    className="c3">We may share your personal information in the following situations:</span>
                </p>
                <p className="c2"><span className="c1">With Service Providers:</span><span
                    className="c3">&nbsp;We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</span>
                </p>
                <p className="c2"><span className="c1">For Business transfers:</span><span
                    className="c3">&nbsp;We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</span>
                </p>
                <p className="c2"><span className="c1">With Affiliates:</span><span
                    className="c3">&nbsp;We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</span>
                </p>
                <p className="c2"><span className="c1">With Business partners:</span><span
                    className="c3">&nbsp;We may share Your information with Our business partners to offer You certain products, services or promotions.</span>
                </p>
                <p className="c2"><span className="c1">With other users:</span><span
                    className="c3">&nbsp;when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</span>
                </p>
                <h2 className="c5" id="h.64nwa08k16lg"><span className="c0">Retention of Your Personal Data</span>
                </h2>
                <p className="c2"><span className="c3">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</span>
                </p>
                <p className="c2"><span className="c3">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</span>
                </p>
                <h2 className="c5" id="h.ugzy5m31ilbx"><span className="c0">Transfer of Your Personal Data</span>
                </h2>
                <p className="c2"><span className="c3">Your information, including Personal Data, is processed at the Company&#39;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to &mdash; and maintained on &mdash; computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</span>
                </p>
                <p className="c2"><span className="c3">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</span>
                </p>
                <p className="c2"><span className="c3">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</span>
                </p>
                <h2 className="c5" id="h.kzltwn9b4wsf"><span className="c0">Disclosure of Your Personal Data</span>
                </h2>
                <h3 className="c7" id="h.bfasimmyeszv"><span
                    className="c4 c1">Business Transactions</span></h3>
                <p className="c2"><span className="c3">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</span>
                </p>
                <h3 className="c7" id="h.908sh0fg7vug"><span
                    className="c4 c1">Law enforcement</span></h3>
                <p className="c2"><span className="c3">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</span>
                </p>
                <h3 className="c7" id="h.aljmzks077y3"><span className="c4 c1">Other legal requirements</span>
                </h3>
                <p className="c2"><span className="c3">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</span>
                </p>
                <p className="c2"><span
                    className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;Comply with a legal obligation</span>
                </p>
                <p className="c2"><span className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;Protect and defend the rights or property of the Company</span>
                </p>
                <p className="c2"><span className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;Prevent or investigate possible wrongdoing in connection with the Service</span>
                </p>
                <p className="c2"><span className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;Protect the personal safety of Users of the Service or the public</span>
                </p>
                <p className="c2"><span
                    className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;Protect against legal liability</span>
                </p>
                <h2 className="c5" id="h.x2wyyoxkkl1c"><span className="c0">Security of Your Personal Data</span>
                </h2>
                <p className="c2"><span className="c3">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</span>
                </p>
                <p className="c2"><span className="c0">Links to Other Websites</span></p>
                <p className="c2"><span className="c3">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&#39;s site. We strongly advise You to review the Privacy Policy of every site You visit.</span>
                </p>
                <p className="c2"><span className="c3">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</span>
                </p>
                <p className="c2"><span className="c0">Changes to this Privacy Policy</span></p>
                <p className="c2"><span className="c3">We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</span>
                </p>
                <p className="c2"><span className="c3">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</span>
                </p>
                <p className="c2"><span className="c3">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</span>
                </p>
                <p className="c2"><span className="c0">Contact Us</span></p>
                <p className="c2"><span className="c3">If you have any questions about this Privacy Policy, You can contact us:</span>
                </p>
                <p className="c2"><span className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;By email: fianchetto@northeastern.edu</span>
                </p>
                <p className="c2"><span
                    className="c3">&middot; &nbsp; &nbsp; &nbsp; &nbsp;By phone number: 1111111111</span>
                </p>
                <p className="c10"><span className="c3"></span></p>


            </div>

        )
    }

}

export default PrivacyPolicy
